'artboards-layout' and 'artboard-grids' showing non-compliant status when grids and layouts are hidden
sketch-hq/sketch-assistants pull request #161
Opened 2020-11-24 08:50 UTC by ines-sketch

- Add two `continue` in case a grid on a artboard is hidden (`isEnabled` is false).
- Update a test that previously checked for "missing" configurations

2020-11-24 12:43 UTC, jedrichards requested changes
Excellent! 👏 

Let's add a changeset to this PR too, so it's "releaseable" later on.

Just run `yarn changeset` and then select a "patch" bump. And the description should be a brief summary of the fix for the changelog.

The result of running that changeset command will be a changeset file added to the repo, which should be included in the PR.

2020-11-24 12:52 UTC, ines-sketch commented
Thank you @jedrichards! I thought the changeset step would only be run later on 😅 
Just pushed the file 🌈

2020-11-24 12:53 UTC, jedrichards approved these changes
🍏

2020-11-25 17:27 UTC, jedrichards commented
@ines-sketch I think you previously didn't have push permissions, that should be fixed now. Feel free to merge this, and then we can look at making a release afterwards.

2020-11-26 08:27 UTC, merged